Seongyoon-Jung/YamYamCoach

- .metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
- .metadata/.plugins/org.eclipse.m2e.logback/0.log
- frontend/src/components/HeaderComponent.vue
- frontend/src/router/index.js
- frontend/src/views/CommunityView.vue
- frontend/src/views/ErrorView.vue
router에 없는 경우에 대응되는 에러페이지 구현
Resolves:# (이슈번호)
<br/>
- 없는 주소로 접속 시에 표시되는 에러페이지 구현
<br/>
<br/>
- 커뮤니티 페이지 구현
<br/>
- [레포 이름 #이슈번호](이슈 주소)
<br/>
> Feat: '에러페이지 기능 구현'

- database/sql/sql_v2_food.sql
sql문 수정 
사진 이미지가 잘뜨는지 보기위해 임의의 사진 주소를 넣었음
어떤 변경 사항이 있나요?
> fix: sql문 수정

- frontend/package-lock.json
- frontend/package.json
- frontend/src/views/board/BoardDetailView.vue
- frontend/src/views/user/LoginView.vue
커뮤니티 댓글 작성 기능 완성
어떤 변경 사항이 있나요?
> Feat: '댓글 작성 기능 완성'

- backend/src/main/java/com/yamyam/diet/controller/DishRecordController.java
- backend/src/main/java/com/yamyam/diet/repository/DishRecordRepository.java
- backend/src/main/java/com/yamyam/diet/service/DishRecordService.java
- frontend/src/components/mainpage/TodayDiet.vue
> Add feature or fix description

- .gitignore
- backend/src/main/java/com/yamyam/diet/controller/DishRecordController.java
- frontend/src/components/mainpage/TodayDiet.vue
기존 음식 기록 시 선택한 음식 수정 가능하게 수정함.
> update select dish_record

- .gitignore
gitignore 파일에 .metadata, .vscode, node_modules 추가
어떤 변경 사항이 있나요?
> fix: 'gitignore 편집'

- backend/.gitignore
백엔드 gitignore 파일 수정
어떤 변경 사항이 있나요?
> fix: backend gitignore

- backend/src/main/java/com/yamyam/controller/BoardController.java
- backend/src/main/java/com/yamyam/dto/request/BoardRequest.java
- backend/src/main/java/com/yamyam/dto/response/BoardResponse.java
- backend/src/main/java/com/yamyam/dto/response/CommentResponse.java
- backend/src/main/java/com/yamyam/entity/BoardEntity.java
- backend/src/main/java/com/yamyam/service/BoardService.java
- backend/src/main/java/com/yamyam/service/BoardServiceImpl.java
- frontend/src/components/board/BoardCard.vue
- frontend/src/router/index.js
- frontend/src/views/board/BoardCreateView.vue
- frontend/src/views/board/BoardDetailView.vue
- frontend/src/views/board/BoardModifyView.vue
- frontend/src/views/board/BoardView.vue
- frontend/src/views/error/ErrorView.vue
이미지 처리에 대한 로직 필요!!!!!!!
게시물 작성, 수정, 삭제 완성
어떤 변경 사항이 있나요?
작성 , 수정 부분에 이미지에 대한 처리를 어떻게 해야하는 지 정해서 수정해야함
> Feat: '게시물 작성, 수정, 삭제 완성'

- backend/src/main/java/com/yamyam/dto/response/CurrentUserResponse.java
- backend/src/main/java/com/yamyam/entity/UserEntity.java
- backend/src/main/java/com/yamyam/service/AuthServiceImpl.java
- backend/src/main/java/com/yamyam/service/UserServiceImpl.java
- frontend/package-lock.json
- frontend/package.json
- frontend/src/main.js
- frontend/src/router/index.js
- frontend/src/store/account.js
- frontend/src/views/admin/AdminView.vue
- frontend/src/views/user/LoginView.vue
admin 페이지 작성. ROLE_ADMIN이라는 권한을 가진 유저만 접근가능
어떤 변경 사항이 있나요?
> Feat: 'admin 페이지 작성'

- frontend/src/views/user/SurveyView.vue
프론트 단에서 설문조사결과가 이상하게 나오는 버그 수정
어떤 변경 사항이 있나요?
결과 사진 다시 만들어서 업로드 예정
> fix: '설문조사 결과'

- backend/src/main/java/com/yamyam/diet/controller/AdminController.java
- backend/src/main/java/com/yamyam/diet/controller/DishRecordController.java
- backend/src/main/java/com/yamyam/diet/repository/DishRepository.java
- backend/src/main/java/com/yamyam/diet/repository/ScheduleDishRepository.java
- backend/src/main/java/com/yamyam/diet/service/DishRecordService.java
- database/sql/add_user_diet_records.sql
- database/sql/combined_dummy_data.sql
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/mainpage/MainChart.vue
- frontend/src/components/mainpage/TodayDiet.vue
- frontend/src/utils/eventBus.js
- frontend/src/views/admin/AdminView.vue
식단 정보 저장 후, Main chart 의 라인 그래프 업데이트
어떤 변경 사항이 있나요?
> update main chart

- backend/src/main/java/com/yamyam/controller/NewsController.java
- frontend/src/components/mainpage/TodayColumn.vue
- frontend/src/store/account.js
todayColumn 컴포넌트를 위한 백쪽 controller 
어떤 변경 사항이 있나요?
> Feat: '뉴스 컴포넌트 기본 controller'

- backend/src/main/java/com/yamyam/controller/NewsController.java
- frontend/src/components/mainpage/TodayColumn.vue
- frontend/src/components/news/NewsCard.vue
> Feat: '프론트 뉴스'

- backend/src/main/resources/application-API-KEY.properties
더미 데이터 data.sql에 추가 및 인코딩 문제 해결
어떤 변경 사항이 있나요?
> add dummy data & force encoding build policy

- backend/src/main/java/com/yamyam/diet/service/DishRecordService.java
DishRecordService.java 의 에러 수정
어떤 변경 사항이 있나요?
> revise error in DishRecordService.java

- backend/build.gradle
- backend/src/main/java/com/yamyam/controller/ClovaController.java
- backend/src/main/java/com/yamyam/dto/request/ClovaRequest.java
- backend/src/main/java/com/yamyam/dto/request/ImageInfo.java
- backend/src/main/java/com/yamyam/service/ClovaService.java
- backend/src/main/java/com/yamyam/service/ClovaServiceImpl.java
- backend/src/main/java/com/yamyam/util/MultipartInputStreamFileResource.java
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.vue
- frontend/src/components/admin/AdminDashboard.vue
- frontend/src/components/admin/AdminDietUpload.vue
- frontend/src/components/admin/AdminUsers.vue
- frontend/src/components/section/AdminHeaderComponent.vue
- frontend/src/router/index.js
- frontend/src/views/admin/AdminView.vue
- frontend/src/views/user/LoginView.vue
Admin 계정으로 로그인 시 바로 어드민 관리 페이지로 갈 수 있도록 어드민페이지 신설
어떤 변경 사항이 있나요?
> Feat 'admin 페이지 신설'"

- frontend/src/components/mainpage/DinnerRecommendation.vue
- frontend/src/components/mainpage/TodayDiet.vue
- frontend/src/components/section/HeaderComponent.vue
- frontend/src/views/home/HomeView.vue
> fix: 메인페이지 변경

- frontend/src/App.vue
- frontend/src/components/news/NewsCard.vue
- frontend/src/components/news/SectionNewsTab.vue
- frontend/src/components/section/HeaderComponent.vue
- frontend/src/router/index.js
- frontend/src/views/news/NewsView.vue
> feat:'뉴스 페이지 작성'

- backend/src/main/java/com/yamyam/controller/BoardController.java
- backend/src/main/java/com/yamyam/service/BoardService.java
- backend/src/main/java/com/yamyam/service/BoardServiceImpl.java
- frontend/src/views/board/BoardCreateView.vue
1. gitignore 재설정
2.  board에 imageurl 담길수있도록 설정완료
어떤 변경 사항이 있나요?
> feat: board 사진 업로드

- backend/src/main/java/com/yamyam/dto/response/BoardResponse.java
- backend/src/main/java/com/yamyam/dto/response/CommentResponse.java
- backend/src/main/java/com/yamyam/dto/response/CurrentUserResponse.java
- backend/src/main/java/com/yamyam/dto/response/UserDetailResponse.java
- backend/src/main/java/com/yamyam/entity/UserEntity.java
- backend/src/main/java/com/yamyam/service/AuthServiceImpl.java
- backend/src/main/java/com/yamyam/service/BoardServiceImpl.java
- backend/src/main/java/com/yamyam/service/CommentServiceImpl.java
- backend/src/main/java/com/yamyam/service/SurveyServiceImpl.java
- backend/src/main/java/com/yamyam/service/UserServiceImpl.java
- backend/src/main/resources/application.properties
- frontend/src/components/board/BoardCard.vue
- frontend/src/components/section/HeaderComponent.vue
- frontend/src/main.js
- frontend/src/store/account.js
- frontend/src/views/board/BoardDetailView.vue
- frontend/src/views/user/LoginView.vue
- frontend/src/views/user/SurveyView.vue
유저 이미지 연동가능하게 만듦
어떤 변경 사항이 있나요?
> feat: user 프로필 사진 등록

- frontend/src/views/admin/AdminView.vue
- frontend/src/views/user/SurveyView.vue
> fix:설문조사 로직 수정

- frontend/src/components/mainpage/MainChart.vue
- frontend/src/views/home/HomeView.vue
> update mainPage components-V2

- frontend/src/components/admin/AdminDiet.vue
- frontend/src/components/board/BoardCard.vue
- frontend/src/router/index.js
- frontend/src/views/board/BoardDetailView.vue
- frontend/src/views/board/BoardView.vue
presigned 오류 변경
어떤 변경 사항이 있나요?
> fix : presigned url 수정

- backend/src/main/java/com/yamyam/controller/FoodsController.java
- backend/src/main/java/com/yamyam/diet/repository/ScheduleDishRepository.java
- backend/src/main/java/com/yamyam/dto/response/FoodsResponse.java
- backend/src/main/java/com/yamyam/service/FoodService.java
- backend/src/main/java/com/yamyam/service/FoodServiceImpl.java
- frontend/src/components/admin/AdminDiet.vue
admin 점심 메뉴 관리 페이지 작성
어떤 변경 사항이 있나요?
> feat: admin 점심메뉴관리 기본

- backend/src/main/java/com/yamyam/dto/request/FoodRequest.java
- frontend/src/components/admin/AdminDiet.vue
- frontend/src/components/admin/ImageCropper.vue
admin 식단 업로드에 이미지 크롭해서 올리도록 기능 추가
어떤 변경 사항이 있나요?
> feat: admin 식단 업로드 이미지 크롭기능 추가

- backend/src/main/resources/application.properties
- frontend/src/components/mainpage/Calendar.vue
- frontend/src/views/home/HomeView.vue
> fix: 메인페이지 css 완벽 수정

- frontend/src/views/error/ErrorView.vue
에러페이지 12기로 착각해서 13기로 바꿈
어떤 변경 사항이 있나요?
> style: 에러 페이지 cli 형식의 감성 문구로 수정

- backend/src/main/java/com/yamyam/diet/controller/MealRecordController.java
- backend/src/main/java/com/yamyam/diet/dto/MealRecordDto.java
- backend/src/main/java/com/yamyam/diet/entity/MealRecord.java
- backend/src/main/java/com/yamyam/diet/repository/MealRecordRepository.java
- backend/src/main/java/com/yamyam/diet/service/MealRecordService.java
- frontend/src/components/mainpage/Calendar.vue
- frontend/src/components/mainpage/MealRecordModal.vue
- recommend/recommend_server.log
> update extra_meal_record & Calandar Part

- frontend/src/components/mainpage/TodayDiet.vue
- recommend/recommend_server.log
> revise todaydiet policy

- frontend/src/components/mainpage/TodayDiet.vue
메인페이지 음식 사진 뜨게 수정
어떤 변경 사항이 있나요?
> fix: 메인페이지 음식 사진 조회 수정

- backend/src/main/java/com/yamyam/recipe/controller/RecipeController.java
- backend/src/main/java/com/yamyam/recipe/service/RecipeService.java
- backend/src/main/java/com/yamyam/recipe/service/RecipeServiceImpl.java
- backend/src/main/java/com/yamyam/service/S3UploadService.java
- backend/src/main/java/com/yamyam/service/S3UploadServiceImpl.java
- frontend/src/components/recipe/RecipeListItem.vue
- frontend/src/components/section/HeaderComponent.vue
- frontend/src/views/recipe/RecipeCreateView.vue
- frontend/src/views/recipe/RecipeDetailView.vue
- frontend/src/views/recipe/RecipeEditView.vue
> update receipe crud

- backend/src/main/java/com/yamyam/recipe/controller/RecipeController.java
- backend/src/main/java/com/yamyam/recipe/service/RecipeServiceImpl.java
- backend/src/main/java/com/yamyam/service/S3UploadServiceImpl.java
- frontend/src/views/recipe/RecipeEditView.vue
- recommend/recommend_server.log
> crud updates in recipes

- backend/src/main/resources/data.sql
- frontend/src/views/board/BoardView.vue
- frontend/src/views/home/Features.vue
커뮤니티 게시판 검색안되는 버그 수정
시연용 아이디인 user@example.com 추가 (data.sql)
어떤 변경 사항이 있나요?
> fix: 커뮤니티 검색안되는 버그 수정 & 시연용 user아이디 작성(data.sql)
